INCLUDE "charmaps.inc"

RSRESET
DEF CARINFO_NAME1 RB 7
DEF CARINFO_NAME2 RB 7
DEF CARINFO_DESC RB 9 * 7 ; 9 chars * 7 lines
DEF CARINFO_SPEEDBARS RB 1 ; 0 to 8
DEF CARINFO_WEIGHTBARS RB 1
DEF CARINFO_MISSILEBARS RB 1
DEF CARINFO_SPECIALBARS RB 1

EXPORT CARINFO_NAME1

SETCHARMAP MainMenuCharmap

SECTION "Car Info", ROMX, ALIGN[8]
CarInfo::
DB "CLASSIC"
DB "       "
DB "Your mom "
DB "gave it  "
DB "to you.  "
DB "         "
DB "         "
DB "Special: "
DB "     None"
DB 5
DB 4
DB 3
DB 0
